apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g1b8yl89l-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g1b8yl89l-nodejs 
  name: g1b8yl89l-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g1b8yl89l-nodejs 
