apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g1b8yl89l-nodejs-gitops
  description: This is GitOps manifest for g1b8yl89l-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=g1b8yl89l-nodejs
    backstage.io/kubernetes-id: g1b8yl89l-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: g1b8yl89l-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g1b8yl89l-nodejs
